{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "continent-climb",
   "metadata": {},
   "source": [
    "# Part 1: Launch a Duet Server and upload data"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "parental-classics",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "🎤  🎸  ♪♪♪ Starting Duet ♫♫♫  🎻  🎹\n",
      "\n",
      "♫♫♫ >\u001b[93m DISCLAIMER\u001b[0m: \u001b[1mDuet is an experimental feature currently in beta.\n",
      "♫♫♫ > Use at your own risk.\n",
      "\u001b[0m\n",
      "\u001b[1m\n",
      "    > ❤️ \u001b[91mLove\u001b[0m \u001b[92mDuet\u001b[0m? \u001b[93mPlease\u001b[0m \u001b[94mconsider\u001b[0m \u001b[95msupporting\u001b[0m \u001b[91mour\u001b[0m \u001b[93mcommunity!\u001b[0m\n",
      "    > https://github.com/sponsors/OpenMined\u001b[1m\n",
      "\n",
      "♫♫♫ > Punching through firewall to OpenGrid Network Node at:\n",
      "♫♫♫ > http://ec2-18-218-7-180.us-east-2.compute.amazonaws.com:5000\n",
      "♫♫♫ >\n",
      "♫♫♫ > ...waiting for response from OpenGrid Network... \n",
      "    > Error: Invalid Client ID. Please try again.\n",
      "    > Error: Invalid Client ID. Please try again.\n",
      "    > Error: Invalid Client ID. Please try again.\n",
      "    > Error: Invalid Client ID. Please try again.\n"
     ]
    }
   ],
   "source": [
    "import syft as sy\n",
    "duet = sy.launch_duet()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "dying-switch",
   "metadata": {},
   "outputs": [],
   "source": [
    "import torch as th\n",
    "from torch.utils.data import Dataset, DataLoader\n",
    "import numpy as np\n",
    "import pandas as pd"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "8ea3c4ef",
   "metadata": {},
   "source": [
    "Read in data"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "af4c5218",
   "metadata": {},
   "outputs": [],
   "source": [
    "df_X_train_0 = pd.read_csv('ETL/X_train_0.csv')\n",
    "df_X_val_0 = pd.read_csv('ETL/X_val_0.csv')\n",
    "df_y_train_0 = pd.read_csv('ETL/y_train_0.csv')\n",
    "df_y_val_0 = pd.read_csv('ETL/y_val_0.csv')"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "77a3e652",
   "metadata": {},
   "source": [
    "Conver to NumPy array"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "abc01c44",
   "metadata": {},
   "outputs": [],
   "source": [
    "X_train_0_np = df_X_train_0.to_numpy()\n",
    "X_val_0_np = df_X_val_0.to_numpy()\n",
    "y_train_0_np = df_y_train_0.to_numpy()\n",
    "y_val_0_np = df_y_val_0.to_numpy()"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "08615318",
   "metadata": {},
   "source": [
    "Convert to Torch tensor"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "2ec01f59",
   "metadata": {},
   "outputs": [],
   "source": [
    "X_train_0 = th.from_numpy(X_train_0_np).float()\n",
    "X_val_0 = th.from_numpy(X_val_0_np).float()\n",
    "y_train_0 = th.from_numpy(y_train_0_np).float()\n",
    "y_val_0 = th.from_numpy(y_val_0_np).float()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "focused-error",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "`searchable` is deprecated please use `pointable` in future\n"
     ]
    }
   ],
   "source": [
    "#data = th.FloatTensor(np.array([5, 15, 25, 35, 45, 55]).reshape(-1, 1))\n",
    "\n",
    "X_train_0 = X_train_0.tag(\"DO1 training X data\")\n",
    "X_train_0 = X_train_0.describe(\"number of samples and features\")\n",
    "\n",
    "data_ptr = X_train_0.send(duet, searchable=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "a8d2c344",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "`searchable` is deprecated please use `pointable` in future\n"
     ]
    }
   ],
   "source": [
    "y_train_0 = y_train_0.tag(\"DO1 training y data\")\n",
    "y_train_0 = y_train_0.describe(\"number of samples and features\")\n",
    "\n",
    "target_ptr = y_train_0.send(duet, searchable=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "circular-commodity",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>ID</th>\n",
       "      <th>Tags</th>\n",
       "      <th>Description</th>\n",
       "      <th>object_type</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>&lt;UID: 51ddc211ecc54ab6b5c14df707fca061&gt;</td>\n",
       "      <td>[DO1 training X data]</td>\n",
       "      <td>number of samples and features</td>\n",
       "      <td>&lt;class 'torch.Tensor'&gt;</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>&lt;UID: 66dedf3c7f2742f8a7c743e41da7397e&gt;</td>\n",
       "      <td>[DO1 training y data]</td>\n",
       "      <td>number of samples and features</td>\n",
       "      <td>&lt;class 'torch.Tensor'&gt;</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                                        ID                   Tags  \\\n",
       "0  <UID: 51ddc211ecc54ab6b5c14df707fca061>  [DO1 training X data]   \n",
       "1  <UID: 66dedf3c7f2742f8a7c743e41da7397e>  [DO1 training y data]   \n",
       "\n",
       "                      Description             object_type  \n",
       "0  number of samples and features  <class 'torch.Tensor'>  \n",
       "1  number of samples and features  <class 'torch.Tensor'>  "
      ]
     },
     "execution_count": 8,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "duet.store.pandas"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "thousand-borough",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[2022-02-06T19:25:36.778605+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: ac25ce3d395146c0b58afa041c9b44fd>:\n",
      "Value: <Storable: 244085>\n",
      "[2022-02-06T19:25:47.609727+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: 5228580006d545bfbf4c41967b59faa2>: To evaluate training progress\n",
      "Value: <Storable: 0.8670288920402527>\n",
      "[2022-02-06T19:25:47.831134+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: e4b77304cda34f0997df6895910cd341>: To evaluate training progress\n",
      "Value: <Storable: 0.21798191964626312>\n",
      "[2022-02-06T19:25:48.055535+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: e2e9955feeec431fb2888e1b33cfe008>: To evaluate training progress\n",
      "Value: <Storable: 0.3428380787372589>\n",
      "[2022-02-06T19:25:48.285918+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: f84095890b4b42bfa5e1d1fe9209644f>: To evaluate training progress\n",
      "Value: <Storable: 0.38612833619117737>\n",
      "[2022-02-06T19:25:48.492365+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: 230c4ac344634dc7a60e2b963599395e>: To evaluate training progress\n",
      "Value: <Storable: 0.36681532859802246>\n",
      "[2022-02-06T19:25:48.711779+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: 369500355ce0476fa1127586aa6f541f>: To evaluate training progress\n",
      "Value: <Storable: 0.31829819083213806>\n",
      "[2022-02-06T19:25:48.924210+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: 435d9b0f4f984b888f1b725819c462db>: To evaluate training progress\n",
      "Value: <Storable: 0.2614467144012451>\n",
      "[2022-02-06T19:25:49.132654+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: cd3e0447f2f24b29b6d6e2894bd9d66c>: To evaluate training progress\n",
      "Value: <Storable: 0.22153319418430328>\n",
      "[2022-02-06T19:25:49.352066+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: 946877bb00e543ff88fc35b68b3e6a35>: To evaluate training progress\n",
      "Value: <Storable: 0.23984304070472717>\n",
      "[2022-02-06T19:25:49.561505+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: 969ea8fba8714a13844d70dbc087775f>: To evaluate training progress\n",
      "Value: <Storable: 0.2770804166793823>\n",
      "[2022-02-06T19:25:49.775934+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: f855c97bcec7484eb8c2072c8bec53f2>: To evaluate training progress\n",
      "Value: <Storable: 0.245829239487648>\n",
      "[2022-02-06T19:25:49.995346+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: 1be6a80e29be461099c27bf33a9549bf>: To evaluate training progress\n",
      "Value: <Storable: 0.22144091129302979>\n",
      "[2022-02-06T19:25:50.214759+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: 9df9243a794d4ba48a82f979b43e0ea9>: To evaluate training progress\n",
      "Value: <Storable: 0.22265461087226868>\n",
      "[2022-02-06T19:25:50.432177+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: c6baac535ce74e0aa1079419d0646d9d>: To evaluate training progress\n",
      "Value: <Storable: 0.23226697742938995>\n",
      "[2022-02-06T19:25:50.652587+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: ba241b62904d4101a5915c3db770d7da>: To evaluate training progress\n",
      "Value: <Storable: 0.23932971060276031>\n",
      "[2022-02-06T19:25:50.868011+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: e2e89dec705d441881045939ea0d906c>: To evaluate training progress\n",
      "Value: <Storable: 0.24007417261600494>\n",
      "[2022-02-06T19:25:51.097398+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: c11f4030168c496582b21075ac665e71>: To evaluate training progress\n",
      "Value: <Storable: 0.234927698969841>\n",
      "[2022-02-06T19:25:51.307835+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: 876f7f6e7e4346d680f5eff0d7c1a0f6>: To evaluate training progress\n",
      "Value: <Storable: 0.22669635713100433>\n",
      "[2022-02-06T19:25:51.527281+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: 96821d118c534901b7a4c07a6d8613f7>: To evaluate training progress\n",
      "Value: <Storable: 0.21936991810798645>\n",
      "[2022-02-06T19:25:51.727712+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: 4e12bd233a264ed5b024bed4c93b87fd>: To evaluate training progress\n",
      "Value: <Storable: 0.21705855429172516>\n",
      "[2022-02-06T19:25:51.930171+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: edb14e5b4a2547df8442dfcab8589b5e>: To evaluate training progress\n",
      "Value: <Storable: 0.22036124765872955>\n",
      "[2022-02-06T19:25:52.126645+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: 818ee8a232e743e39394bbc75e9169c5>: To evaluate training progress\n",
      "Value: <Storable: 0.22527621686458588>\n",
      "[2022-02-06T19:25:52.336085+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: 6b374d7207b6421cb330d9aee63cbbd5>: To evaluate training progress\n",
      "Value: <Storable: 0.2268221527338028>\n",
      "[2022-02-06T19:25:52.553503+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: 765538664c414809a87829200f7111e6>: To evaluate training progress\n",
      "Value: <Storable: 0.22375473380088806>\n",
      "[2022-02-06T19:25:52.772915+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: 64a0bcc06cdf4ddaa8992fcfa5bbf1c0>: To evaluate training progress\n",
      "Value: <Storable: 0.2184683233499527>\n",
      "[2022-02-06T19:26:01.368502+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: f208b622f39b4e368d1242b6c3dbea58>:\n",
      "Value: <Storable: [Parameter containing:tensor([[-0.6705, -0.3303, -0.5241, ..., -0.6079, -0.3797, -0.2847],    [-0.4322, -0.6333, -0.6553, ..., -0.5350, -0.5634, -0.4677],    [-0.0275, -0.0378, 0.0638, ..., -0.8276, -0.0713, 0.4437],    ...,    [ 0.0864, 0.1229, -0.0402, ..., 0.3964, 0.4236, 0.4213],    [-0.4928, -0.4525, -0.6064, ..., -0.5419, -0.3980, -0.5594],    [-0.0497, -0.1080, -0.2481, ..., -0.1189, -0.1485, 0.1548]],    requires_grad=True), Parameter containing:tensor([-0.5262, -0.5487, 0.1218, -0.4626, -0.3093, -0.7089, 0.0703, -0.6706,     0.2373, -0.5690, -0.4055, -0.5815, 0.3341, -0.4520, -0.0122, -0.4956,    -0.4243, -0.5068, 0.3410, -0.6791, -0.2684, 0.1148, 0.4422, -0.5914,     0.4206, -0.5996, 0.4034, 0.2508, 0.2572, -0.4342, -0.6252],    requires_grad=True), Parameter containing:tensor([[ 0.3320, -0.4902, -0.0399, 0.2196, 0.4279, -0.4430, -0.0025, -0.4319,     -0.1332, 0.4993, -0.4381, 0.3149, -0.1719, 0.1590, -0.1019, -0.4788,     -0.4794, -0.5373, -0.1979, -0.5026, 0.5193, -0.0400, -0.2100, -0.4833,     -0.2589, -0.4527, -0.2317, -0.1294, -0.0629, -0.5143, -0.4621]],    requires_grad=True), Parameter containing:tensor([-0.4759], requires_grad=True)]>\n",
      "[2022-02-06T19:26:01.687751+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: 97f4f86edddc4383ac6bfd133e511665>:\n",
      "Value: <Storable: 'in_features=39, out_features=31, bias=True'>\n",
      "[2022-02-06T19:26:01.813835+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: 84c1cb699d3446479ad18ed33ecb00a1>:\n",
      "Value: <Storable: OrderedDict([('weight', tensor([[-0.6705, -0.3303, -0.5241, ..., -0.6079, -0.3797, -0.2847],    [-0.4322, -0.6333, -0.6553, ..., -0.5350, -0.5634, -0.4677],    [-0.0275, -0.0378, 0.0638, ..., -0.8276, -0.0713, 0.4437],    ...,    [ 0.0864, 0.1229, -0.0402, ..., 0.3964, 0.4236, 0.4213],    [-0.4928, -0.4525, -0.6064, ..., -0.5419, -0.3980, -0.5594],    [-0.0497, -0.1080, -0.2481, ..., -0.1189, -0.1485, 0.1548]])), ('bias', tensor([-0.5262, -0.5487, 0.1218, -0.4626, -0.3093, -0.7089, 0.0703, -0.6706,     0.2373, -0.5690, -0.4055, -0.5815, 0.3341, -0.4520, -0.0122, -0.4956,    -0.4243, -0.5068, 0.3410, -0.6791, -0.2684, 0.1148, 0.4422, -0.5914,     0.4206, -0.5996, 0.4034, 0.2508, 0.2572, -0.4342, -0.6252]))])>\n",
      "[2022-02-06T19:26:01.937012+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: 084dc3fc4c3d4d8cba17bdcd00c9f5b6>:\n",
      "Value: <Storable: 'in_features=31, out_features=1, bias=True'>\n",
      "[2022-02-06T19:26:02.050427+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: 91d9e698fed645f98ffb9f7baefa0be6>:\n",
      "Value: <Storable: OrderedDict([('weight', tensor([[ 0.3320, -0.4902, -0.0399, 0.2196, 0.4279, -0.4430, -0.0025, -0.4319,     -0.1332, 0.4993, -0.4381, 0.3149, -0.1719, 0.1590, -0.1019, -0.4788,     -0.4794, -0.5373, -0.1979, -0.5026, 0.5193, -0.0400, -0.2100, -0.4833,     -0.2589, -0.4527, -0.2317, -0.1294, -0.0629, -0.5143, -0.4621]])), ('bias', tensor([-0.4759]))])>\n",
      "[2022-02-06T19:26:03.161616+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: 7754d5b539f7431199486ff4f5dc7fda>:\n",
      "Value: <Storable: 'p=0.1240939274430275, inplace=False'>\n",
      "[2022-02-06T19:26:03.291412+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: e44b141812fd47099cd471a944fb1dff>:\n",
      "Value: <Storable: OrderedDict()>\n",
      "[2022-02-06T19:26:04.410794+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: 959e58bfdbcc48038a0dc8b930d40b56>:\n",
      "Value: <Storable: ''>\n",
      "[2022-02-06T19:26:04.533902+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: ff24e6ee708441d4876a075ea434ab05>:\n",
      "Value: <Storable: OrderedDict()>\n",
      "[2022-02-06T19:36:42.622541+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: e15cd84ca0d64072823f99369b58977f>: To run test and inference locally\n",
      "Value: <Storable: False>\n",
      "[2022-02-06T19:49:06.487932+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: 979a13a54301460ca9779baa6edaf4d8>:\n",
      "Value: <Storable: 3814>\n",
      "[2022-02-06T19:49:06.557750+0000][CRITICAL][logger]][65548] Expected 2 or more dimensions (got 1)\n",
      "[2022-02-06T19:49:06.558777+0000][CRITICAL][logger]][65548] Expected 2 or more dimensions (got 1)\n",
      "Exception in callback AsyncIOEventEmitter._emit_run.<locals>._callback(<Task finishe...ons (got 1)')>) at C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\pyee\\_asyncio.py:57\n",
      "handle: <Handle AsyncIOEventEmitter._emit_run.<locals>._callback(<Task finishe...ons (got 1)')>) at C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\pyee\\_asyncio.py:57>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\pyee\\_asyncio.py\", line 64, in _callback\n",
      "    self.emit(\"error\", exc)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\pyee\\_base.py\", line 118, in emit\n",
      "    self._emit_handle_potential_error(event, args[0] if args else None)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\pyee\\_base.py\", line 88, in _emit_handle_potential_error\n",
      "    raise error\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\asyncio\\tasks.py\", line 280, in __step\n",
      "    result = coro.send(None)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\grid\\connections\\webrtc.py\", line 233, in on_message\n",
      "    await self.consumer(msg=message)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\grid\\connections\\webrtc.py\", line 449, in consumer\n",
      "    traceback_and_raise(e)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\logger.py\", line 61, in traceback_and_raise\n",
      "    raise e\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\grid\\connections\\webrtc.py\", line 434, in consumer\n",
      "    self.recv_immediate_msg_without_reply(msg=_msg)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\grid\\connections\\webrtc.py\", line 490, in recv_immediate_msg_without_reply\n",
      "    traceback_and_raise(e)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\logger.py\", line 61, in traceback_and_raise\n",
      "    raise e\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\grid\\connections\\webrtc.py\", line 485, in recv_immediate_msg_without_reply\n",
      "    self.node.recv_immediate_msg_without_reply(msg=msg)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\core\\node\\common\\node.py\", line 399, in recv_immediate_msg_without_reply\n",
      "    self.process_message(msg=msg, router=self.immediate_msg_without_reply_router)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\core\\node\\common\\node.py\", line 481, in process_message\n",
      "    result = service.process(\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\core\\node\\common\\service\\obj_action_service.py\", line 27, in process\n",
      "    msg.execute_action(node=node, verify_key=verify_key)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\core\\node\\common\\action\\function_or_constructor_action.py\", line 126, in execute_action\n",
      "    result = method(*upcasted_args, **upcasted_kwargs)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\torch\\nn\\functional.py\", line 2381, in nll_loss\n",
      "    raise ValueError(\"Expected 2 or more dimensions (got {})\".format(dim))\n",
      "ValueError: Expected 2 or more dimensions (got 1)\n",
      "[2022-02-06T19:49:06.566733+0000][CRITICAL][logger]][65548] execute_action on torch.Tensor.backward failed due to missing object at: <UID: 91571401be8046fb96dd10f8a41871b6>\n",
      "[2022-02-06T19:49:06.568817+0000][CRITICAL][logger]][65548] <class 'syft.core.store.store_memory.MemoryStore'> __delitem__ error <UID: 16c2cd1c14ab4c118d1df4a1a31f35b0>.\n",
      "[2022-02-06T19:49:06.571718+0000][CRITICAL][logger]][65548] execute_action on torch.Tensor.item failed due to missing object at: <UID: 91571401be8046fb96dd10f8a41871b6>\n",
      "[2022-02-06T19:51:06.305362+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: e3991e4489f74c4ebb9bee7bb38e69bc>:\n",
      "Value: <Storable: 3814>\n",
      "[2022-02-06T19:51:06.453196+0000][CRITICAL][logger]][65548] Expected 2 or more dimensions (got 1)\n",
      "[2022-02-06T19:51:06.454487+0000][CRITICAL][logger]][65548] Expected 2 or more dimensions (got 1)\n",
      "Exception in callback AsyncIOEventEmitter._emit_run.<locals>._callback(<Task finishe...ons (got 1)')>) at C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\pyee\\_asyncio.py:57\n",
      "handle: <Handle AsyncIOEventEmitter._emit_run.<locals>._callback(<Task finishe...ons (got 1)')>) at C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\pyee\\_asyncio.py:57>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\pyee\\_asyncio.py\", line 64, in _callback\n",
      "    self.emit(\"error\", exc)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\pyee\\_base.py\", line 118, in emit\n",
      "    self._emit_handle_potential_error(event, args[0] if args else None)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\pyee\\_base.py\", line 88, in _emit_handle_potential_error\n",
      "    raise error\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\asyncio\\tasks.py\", line 280, in __step\n",
      "    result = coro.send(None)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\grid\\connections\\webrtc.py\", line 233, in on_message\n",
      "    await self.consumer(msg=message)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\grid\\connections\\webrtc.py\", line 449, in consumer\n",
      "    traceback_and_raise(e)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\logger.py\", line 61, in traceback_and_raise\n",
      "    raise e\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\grid\\connections\\webrtc.py\", line 434, in consumer\n",
      "    self.recv_immediate_msg_without_reply(msg=_msg)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\grid\\connections\\webrtc.py\", line 490, in recv_immediate_msg_without_reply\n",
      "    traceback_and_raise(e)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\logger.py\", line 61, in traceback_and_raise\n",
      "    raise e\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\grid\\connections\\webrtc.py\", line 485, in recv_immediate_msg_without_reply\n",
      "    self.node.recv_immediate_msg_without_reply(msg=msg)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\core\\node\\common\\node.py\", line 399, in recv_immediate_msg_without_reply\n",
      "    self.process_message(msg=msg, router=self.immediate_msg_without_reply_router)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\core\\node\\common\\node.py\", line 481, in process_message\n",
      "    result = service.process(\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\core\\node\\common\\service\\obj_action_service.py\", line 27, in process\n",
      "    msg.execute_action(node=node, verify_key=verify_key)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\core\\node\\common\\action\\function_or_constructor_action.py\", line 126, in execute_action\n",
      "    result = method(*upcasted_args, **upcasted_kwargs)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\torch\\nn\\functional.py\", line 2381, in nll_loss\n",
      "    raise ValueError(\"Expected 2 or more dimensions (got {})\".format(dim))\n",
      "ValueError: Expected 2 or more dimensions (got 1)\n",
      "[2022-02-06T19:51:06.457509+0000][CRITICAL][logger]][65548] execute_action on torch.Tensor.backward failed due to missing object at: <UID: 5ed2b9c8999e4cd2a8ce87a93d9155ec>\n",
      "[2022-02-06T19:51:06.459517+0000][CRITICAL][logger]][65548] <class 'syft.core.store.store_memory.MemoryStore'> __delitem__ error <UID: 89854eebfd774cb282476d8148f516c4>.\n",
      "[2022-02-06T19:51:06.465501+0000][CRITICAL][logger]][65548] execute_action on torch.Tensor.item failed due to missing object at: <UID: 5ed2b9c8999e4cd2a8ce87a93d9155ec>\n",
      "[2022-02-06T19:51:06.471475+0000][CRITICAL][logger]][65548] <class 'syft.core.store.store_memory.MemoryStore'> __getitem__ error <UID: 27b7ddd248d146cd86d19614f13ee876> <UID: 27b7ddd248d146cd86d19614f13ee876>\n",
      "[2022-02-06T19:51:06.471475+0000][CRITICAL][logger]][65548] <UID: 27b7ddd248d146cd86d19614f13ee876>\n",
      "[2022-02-06T19:51:06.472450+0000][CRITICAL][logger]][65548] <UID: 27b7ddd248d146cd86d19614f13ee876>\n",
      "[2022-02-06T19:51:06.473482+0000][CRITICAL][logger]][65548] <UID: 27b7ddd248d146cd86d19614f13ee876>\n",
      "Exception in callback AsyncIOEventEmitter._emit_run.<locals>._callback(<Task finishe...614f13ee876>)>) at C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\pyee\\_asyncio.py:57\n",
      "handle: <Handle AsyncIOEventEmitter._emit_run.<locals>._callback(<Task finishe...614f13ee876>)>) at C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\pyee\\_asyncio.py:57>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\pyee\\_asyncio.py\", line 64, in _callback\n",
      "    self.emit(\"error\", exc)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\pyee\\_base.py\", line 118, in emit\n",
      "    self._emit_handle_potential_error(event, args[0] if args else None)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\pyee\\_base.py\", line 88, in _emit_handle_potential_error\n",
      "    raise error\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\asyncio\\tasks.py\", line 280, in __step\n",
      "    result = coro.send(None)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\grid\\connections\\webrtc.py\", line 233, in on_message\n",
      "    await self.consumer(msg=message)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\grid\\connections\\webrtc.py\", line 449, in consumer\n",
      "    traceback_and_raise(e)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\logger.py\", line 61, in traceback_and_raise\n",
      "    raise e\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\grid\\connections\\webrtc.py\", line 434, in consumer\n",
      "    self.recv_immediate_msg_without_reply(msg=_msg)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\grid\\connections\\webrtc.py\", line 490, in recv_immediate_msg_without_reply\n",
      "    traceback_and_raise(e)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\logger.py\", line 61, in traceback_and_raise\n",
      "    raise e\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\grid\\connections\\webrtc.py\", line 485, in recv_immediate_msg_without_reply\n",
      "    self.node.recv_immediate_msg_without_reply(msg=msg)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\core\\node\\common\\node.py\", line 399, in recv_immediate_msg_without_reply\n",
      "    self.process_message(msg=msg, router=self.immediate_msg_without_reply_router)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\core\\node\\common\\node.py\", line 481, in process_message\n",
      "    result = service.process(\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\core\\node\\common\\service\\obj_action_service.py\", line 27, in process\n",
      "    msg.execute_action(node=node, verify_key=verify_key)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\core\\node\\common\\action\\run_class_method_action.py\", line 126, in execute_action\n",
      "    r_arg = node.store[arg.id_at_location]\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\core\\store\\store_memory.py\", line 66, in __getitem__\n",
      "    traceback_and_raise(e)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\logger.py\", line 61, in traceback_and_raise\n",
      "    raise e\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\core\\store\\store_memory.py\", line 63, in __getitem__\n",
      "    return self._objects[key]\n",
      "KeyError: <UID: 27b7ddd248d146cd86d19614f13ee876>\n",
      "[2022-02-06T19:51:06.521312+0000][CRITICAL][logger]][65548] <class 'syft.core.store.store_memory.MemoryStore'> __getitem__ error <UID: 27b7ddd248d146cd86d19614f13ee876> <UID: 27b7ddd248d146cd86d19614f13ee876>\n",
      "[2022-02-06T19:51:06.521312+0000][CRITICAL][logger]][65548] <UID: 27b7ddd248d146cd86d19614f13ee876>\n",
      "[2022-02-06T19:51:06.522308+0000][CRITICAL][logger]][65548] <UID: 27b7ddd248d146cd86d19614f13ee876>\n",
      "[2022-02-06T19:51:06.523305+0000][CRITICAL][logger]][65548] <UID: 27b7ddd248d146cd86d19614f13ee876>\n",
      "Exception in callback AsyncIOEventEmitter._emit_run.<locals>._callback(<Task finishe...614f13ee876>)>) at C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\pyee\\_asyncio.py:57\n",
      "handle: <Handle AsyncIOEventEmitter._emit_run.<locals>._callback(<Task finishe...614f13ee876>)>) at C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\pyee\\_asyncio.py:57>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\pyee\\_asyncio.py\", line 64, in _callback\n",
      "    self.emit(\"error\", exc)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\pyee\\_base.py\", line 118, in emit\n",
      "    self._emit_handle_potential_error(event, args[0] if args else None)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\pyee\\_base.py\", line 88, in _emit_handle_potential_error\n",
      "    raise error\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\asyncio\\tasks.py\", line 280, in __step\n",
      "    result = coro.send(None)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\grid\\connections\\webrtc.py\", line 233, in on_message\n",
      "    await self.consumer(msg=message)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\grid\\connections\\webrtc.py\", line 449, in consumer\n",
      "    traceback_and_raise(e)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\logger.py\", line 61, in traceback_and_raise\n",
      "    raise e\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\grid\\connections\\webrtc.py\", line 434, in consumer\n",
      "    self.recv_immediate_msg_without_reply(msg=_msg)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\grid\\connections\\webrtc.py\", line 490, in recv_immediate_msg_without_reply\n",
      "    traceback_and_raise(e)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\logger.py\", line 61, in traceback_and_raise\n",
      "    raise e\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\grid\\connections\\webrtc.py\", line 485, in recv_immediate_msg_without_reply\n",
      "    self.node.recv_immediate_msg_without_reply(msg=msg)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\core\\node\\common\\node.py\", line 399, in recv_immediate_msg_without_reply\n",
      "    self.process_message(msg=msg, router=self.immediate_msg_without_reply_router)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\core\\node\\common\\node.py\", line 481, in process_message\n",
      "    result = service.process(\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\core\\node\\domain\\service\\request_message.py\", line 222, in process\n",
      "    msg.object_tags.extend(node.store[msg.object_id]._tags)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\core\\store\\store_memory.py\", line 66, in __getitem__\n",
      "    traceback_and_raise(e)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\logger.py\", line 61, in traceback_and_raise\n",
      "    raise e\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\core\\store\\store_memory.py\", line 63, in __getitem__\n",
      "    return self._objects[key]\n",
      "KeyError: <UID: 27b7ddd248d146cd86d19614f13ee876>\n",
      "[2022-02-06T19:51:06.559210+0000][CRITICAL][logger]][65548] <class 'syft.core.store.store_memory.MemoryStore'> __delitem__ error <UID: 5ed2b9c8999e4cd2a8ce87a93d9155ec>.\n",
      "[2022-02-06T19:51:06.561205+0000][CRITICAL][logger]][65548] <class 'syft.core.store.store_memory.MemoryStore'> __delitem__ error <UID: 27b7ddd248d146cd86d19614f13ee876>.\n",
      "[2022-02-06T19:51:06.563199+0000][CRITICAL][logger]][65548] <class 'syft.core.store.store_memory.MemoryStore'> __delitem__ error <UID: 60581f48b66545b9ad4274f04524e41a>.\n",
      "[2022-02-06T19:52:33.576236+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: 8e3369913a954b098cc341958108a440>:\n",
      "Value: <Storable: 3814>\n",
      "[2022-02-06T19:52:33.717248+0000][CRITICAL][logger]][65548] Expected 2 or more dimensions (got 1)\n",
      "[2022-02-06T19:52:33.718245+0000][CRITICAL][logger]][65548] Expected 2 or more dimensions (got 1)\n",
      "Exception in callback AsyncIOEventEmitter._emit_run.<locals>._callback(<Task finishe...ons (got 1)')>) at C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\pyee\\_asyncio.py:57\n",
      "handle: <Handle AsyncIOEventEmitter._emit_run.<locals>._callback(<Task finishe...ons (got 1)')>) at C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\pyee\\_asyncio.py:57>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\pyee\\_asyncio.py\", line 64, in _callback\n",
      "    self.emit(\"error\", exc)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\pyee\\_base.py\", line 118, in emit\n",
      "    self._emit_handle_potential_error(event, args[0] if args else None)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\pyee\\_base.py\", line 88, in _emit_handle_potential_error\n",
      "    raise error\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\asyncio\\tasks.py\", line 280, in __step\n",
      "    result = coro.send(None)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\grid\\connections\\webrtc.py\", line 233, in on_message\n",
      "    await self.consumer(msg=message)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\grid\\connections\\webrtc.py\", line 449, in consumer\n",
      "    traceback_and_raise(e)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\logger.py\", line 61, in traceback_and_raise\n",
      "    raise e\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\grid\\connections\\webrtc.py\", line 434, in consumer\n",
      "    self.recv_immediate_msg_without_reply(msg=_msg)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\grid\\connections\\webrtc.py\", line 490, in recv_immediate_msg_without_reply\n",
      "    traceback_and_raise(e)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\logger.py\", line 61, in traceback_and_raise\n",
      "    raise e\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\grid\\connections\\webrtc.py\", line 485, in recv_immediate_msg_without_reply\n",
      "    self.node.recv_immediate_msg_without_reply(msg=msg)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\core\\node\\common\\node.py\", line 399, in recv_immediate_msg_without_reply\n",
      "    self.process_message(msg=msg, router=self.immediate_msg_without_reply_router)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\core\\node\\common\\node.py\", line 481, in process_message\n",
      "    result = service.process(\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\core\\node\\common\\service\\obj_action_service.py\", line 27, in process\n",
      "    msg.execute_action(node=node, verify_key=verify_key)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\core\\node\\common\\action\\function_or_constructor_action.py\", line 126, in execute_action\n",
      "    result = method(*upcasted_args, **upcasted_kwargs)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\torch\\nn\\functional.py\", line 2381, in nll_loss\n",
      "    raise ValueError(\"Expected 2 or more dimensions (got {})\".format(dim))\n",
      "ValueError: Expected 2 or more dimensions (got 1)\n",
      "[2022-02-06T19:52:34.048328+0000][CRITICAL][logger]][65548] execute_action on torch.Tensor.backward failed due to missing object at: <UID: f3e7b33ce6fd4a3083a21b811ec1d1f5>\n",
      "[2022-02-06T19:52:34.050347+0000][CRITICAL][logger]][65548] <class 'syft.core.store.store_memory.MemoryStore'> __delitem__ error <UID: 2ede89c12f8c44669203b3ccda452031>.\n",
      "[2022-02-06T19:52:34.055347+0000][CRITICAL][logger]][65548] execute_action on torch.Tensor.item failed due to missing object at: <UID: f3e7b33ce6fd4a3083a21b811ec1d1f5>\n",
      "[2022-02-06T19:52:34.061293+0000][CRITICAL][logger]][65548] <class 'syft.core.store.store_memory.MemoryStore'> __getitem__ error <UID: 71a17aab490640c9a11beb73989b7d41> <UID: 71a17aab490640c9a11beb73989b7d41>\n",
      "[2022-02-06T19:52:34.062290+0000][CRITICAL][logger]][65548] <UID: 71a17aab490640c9a11beb73989b7d41>\n",
      "[2022-02-06T19:52:34.062290+0000][CRITICAL][logger]][65548] <UID: 71a17aab490640c9a11beb73989b7d41>\n",
      "[2022-02-06T19:52:34.062290+0000][CRITICAL][logger]][65548] <UID: 71a17aab490640c9a11beb73989b7d41>\n",
      "Exception in callback AsyncIOEventEmitter._emit_run.<locals>._callback(<Task finishe...b73989b7d41>)>) at C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\pyee\\_asyncio.py:57\n",
      "handle: <Handle AsyncIOEventEmitter._emit_run.<locals>._callback(<Task finishe...b73989b7d41>)>) at C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\pyee\\_asyncio.py:57>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\pyee\\_asyncio.py\", line 64, in _callback\n",
      "    self.emit(\"error\", exc)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\pyee\\_base.py\", line 118, in emit\n",
      "    self._emit_handle_potential_error(event, args[0] if args else None)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\pyee\\_base.py\", line 88, in _emit_handle_potential_error\n",
      "    raise error\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\asyncio\\tasks.py\", line 280, in __step\n",
      "    result = coro.send(None)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\grid\\connections\\webrtc.py\", line 233, in on_message\n",
      "    await self.consumer(msg=message)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\grid\\connections\\webrtc.py\", line 449, in consumer\n",
      "    traceback_and_raise(e)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\logger.py\", line 61, in traceback_and_raise\n",
      "    raise e\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\grid\\connections\\webrtc.py\", line 434, in consumer\n",
      "    self.recv_immediate_msg_without_reply(msg=_msg)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\grid\\connections\\webrtc.py\", line 490, in recv_immediate_msg_without_reply\n",
      "    traceback_and_raise(e)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\logger.py\", line 61, in traceback_and_raise\n",
      "    raise e\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\grid\\connections\\webrtc.py\", line 485, in recv_immediate_msg_without_reply\n",
      "    self.node.recv_immediate_msg_without_reply(msg=msg)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\core\\node\\common\\node.py\", line 399, in recv_immediate_msg_without_reply\n",
      "    self.process_message(msg=msg, router=self.immediate_msg_without_reply_router)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\core\\node\\common\\node.py\", line 481, in process_message\n",
      "    result = service.process(\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\core\\node\\common\\service\\obj_action_service.py\", line 27, in process\n",
      "    msg.execute_action(node=node, verify_key=verify_key)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\core\\node\\common\\action\\run_class_method_action.py\", line 126, in execute_action\n",
      "    r_arg = node.store[arg.id_at_location]\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\core\\store\\store_memory.py\", line 66, in __getitem__\n",
      "    traceback_and_raise(e)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\logger.py\", line 61, in traceback_and_raise\n",
      "    raise e\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\core\\store\\store_memory.py\", line 63, in __getitem__\n",
      "    return self._objects[key]\n",
      "KeyError: <UID: 71a17aab490640c9a11beb73989b7d41>\n",
      "[2022-02-06T19:52:34.067277+0000][CRITICAL][logger]][65548] <class 'syft.core.store.store_memory.MemoryStore'> __getitem__ error <UID: 71a17aab490640c9a11beb73989b7d41> <UID: 71a17aab490640c9a11beb73989b7d41>\n",
      "[2022-02-06T19:52:34.067277+0000][CRITICAL][logger]][65548] <UID: 71a17aab490640c9a11beb73989b7d41>\n",
      "[2022-02-06T19:52:34.068274+0000][CRITICAL][logger]][65548] <UID: 71a17aab490640c9a11beb73989b7d41>\n",
      "[2022-02-06T19:52:34.068274+0000][CRITICAL][logger]][65548] <UID: 71a17aab490640c9a11beb73989b7d41>\n",
      "Exception in callback AsyncIOEventEmitter._emit_run.<locals>._callback(<Task finishe...b73989b7d41>)>) at C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\pyee\\_asyncio.py:57\n",
      "handle: <Handle AsyncIOEventEmitter._emit_run.<locals>._callback(<Task finishe...b73989b7d41>)>) at C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\pyee\\_asyncio.py:57>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\pyee\\_asyncio.py\", line 64, in _callback\n",
      "    self.emit(\"error\", exc)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\pyee\\_base.py\", line 118, in emit\n",
      "    self._emit_handle_potential_error(event, args[0] if args else None)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\pyee\\_base.py\", line 88, in _emit_handle_potential_error\n",
      "    raise error\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\asyncio\\tasks.py\", line 280, in __step\n",
      "    result = coro.send(None)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\grid\\connections\\webrtc.py\", line 233, in on_message\n",
      "    await self.consumer(msg=message)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\grid\\connections\\webrtc.py\", line 449, in consumer\n",
      "    traceback_and_raise(e)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\logger.py\", line 61, in traceback_and_raise\n",
      "    raise e\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\grid\\connections\\webrtc.py\", line 434, in consumer\n",
      "    self.recv_immediate_msg_without_reply(msg=_msg)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\grid\\connections\\webrtc.py\", line 490, in recv_immediate_msg_without_reply\n",
      "    traceback_and_raise(e)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\logger.py\", line 61, in traceback_and_raise\n",
      "    raise e\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\grid\\connections\\webrtc.py\", line 485, in recv_immediate_msg_without_reply\n",
      "    self.node.recv_immediate_msg_without_reply(msg=msg)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\core\\node\\common\\node.py\", line 399, in recv_immediate_msg_without_reply\n",
      "    self.process_message(msg=msg, router=self.immediate_msg_without_reply_router)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\core\\node\\common\\node.py\", line 481, in process_message\n",
      "    result = service.process(\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\core\\node\\domain\\service\\request_message.py\", line 222, in process\n",
      "    msg.object_tags.extend(node.store[msg.object_id]._tags)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\core\\store\\store_memory.py\", line 66, in __getitem__\n",
      "    traceback_and_raise(e)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\logger.py\", line 61, in traceback_and_raise\n",
      "    raise e\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\core\\store\\store_memory.py\", line 63, in __getitem__\n",
      "    return self._objects[key]\n",
      "KeyError: <UID: 71a17aab490640c9a11beb73989b7d41>\n",
      "[2022-02-06T19:52:34.093208+0000][CRITICAL][logger]][65548] <class 'syft.core.store.store_memory.MemoryStore'> __delitem__ error <UID: f3e7b33ce6fd4a3083a21b811ec1d1f5>.\n",
      "[2022-02-06T19:52:34.095202+0000][CRITICAL][logger]][65548] <class 'syft.core.store.store_memory.MemoryStore'> __delitem__ error <UID: 71a17aab490640c9a11beb73989b7d41>.\n",
      "[2022-02-06T19:52:34.096199+0000][CRITICAL][logger]][65548] <class 'syft.core.store.store_memory.MemoryStore'> __delitem__ error <UID: e30db65347dc4a7aa4aca59f15fc996e>.\n",
      "[2022-02-06T19:53:01.122899+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: 2da5d89ffbb0489bb615635ed4533b9c>: To evaluate training progress\n",
      "Value: <Storable: 0.21987323462963104>\n",
      "[2022-02-06T19:53:01.337325+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: 64c1eb13510a4aca959d1c526d5900d1>: To evaluate training progress\n",
      "Value: <Storable: 0.2208656221628189>\n",
      "[2022-02-06T19:53:01.561726+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: b3215aeb8f9745b9b3641607971d786e>: To evaluate training progress\n",
      "Value: <Storable: 0.2204836905002594>\n",
      "[2022-02-06T19:53:01.779142+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: 03e819c384a5420b9cdaa5fca0efb438>: To evaluate training progress\n",
      "Value: <Storable: 0.21841537952423096>\n",
      "[2022-02-06T19:53:01.993569+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: 8a7edd7b77bb410ea07c7043b11863b1>: To evaluate training progress\n",
      "Value: <Storable: 0.21590182185173035>\n",
      "[2022-02-06T19:53:02.215975+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: 4f31bd1ed2f9474683d5638f63f4f24f>: To evaluate training progress\n",
      "Value: <Storable: 0.21407213807106018>\n",
      "[2022-02-06T19:53:03.336976+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: b0b440092bde4a62b41953cc57142b22>: To evaluate training progress\n",
      "Value: <Storable: 0.21336041390895844>\n",
      "[2022-02-06T19:53:03.544420+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: cc1abcb420864c53ab2b07d2f76600b9>: To evaluate training progress\n",
      "Value: <Storable: 0.21356450021266937>\n",
      "[2022-02-06T19:53:03.758846+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: 4aa2087efc944f1eafa54ad62671f7cc>: To evaluate training progress\n",
      "Value: <Storable: 0.2147929072380066>\n",
      "[2022-02-06T19:53:03.968286+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: cc8cbdc66e1c4de0b51d89e59a890b9a>: To evaluate training progress\n",
      "Value: <Storable: 0.21574881672859192>\n",
      "[2022-02-06T19:53:04.186702+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: 2d1db9523eda40fba551412aedc3ba1b>: To evaluate training progress\n",
      "Value: <Storable: 0.21574749052524567>\n",
      "[2022-02-06T19:53:04.406117+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: 5ded3eec2c854a60a27d7c80863f0258>: To evaluate training progress\n",
      "Value: <Storable: 0.21456104516983032>\n",
      "[2022-02-06T19:53:04.623533+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: d7dca9d4f327416089829082c6028980>: To evaluate training progress\n",
      "Value: <Storable: 0.2136431783437729>\n",
      "[2022-02-06T19:53:04.839955+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: 1b49b8c1d150458ab8839bec75cd091f>: To evaluate training progress\n",
      "Value: <Storable: 0.2126656025648117>\n",
      "[2022-02-06T19:53:05.065352+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: 2e797b749f4e4180bdbbd6f9e25fe097>: To evaluate training progress\n",
      "Value: <Storable: 0.2124195396900177>\n",
      "[2022-02-06T19:53:05.295735+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: cb151889ed174d1ca87f251fc598f3ff>: To evaluate training progress\n",
      "Value: <Storable: 0.21255812048912048>\n",
      "[2022-02-06T19:53:05.514152+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: 875c0396539b41beb6203784ebec7f26>: To evaluate training progress\n",
      "Value: <Storable: 0.2128213495016098>\n",
      "[2022-02-06T19:53:05.744534+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: 795f3003657e48fe9a79a502891de865>: To evaluate training progress\n",
      "Value: <Storable: 0.2129717469215393>\n",
      "[2022-02-06T19:53:05.950982+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: 9e29f3a79e1848ffaf0bd5b75aa88836>: To evaluate training progress\n",
      "Value: <Storable: 0.21298201382160187>\n",
      "[2022-02-06T19:53:06.175382+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: 5833a2d82a2b4f9fb5f4af564665f21e>: To evaluate training progress\n",
      "Value: <Storable: 0.21235740184783936>\n",
      "[2022-02-06T19:53:06.376843+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: 848a2a809b534942ab58e57ffece3aa2>: To evaluate training progress\n",
      "Value: <Storable: 0.2116430699825287>\n",
      "[2022-02-06T19:53:06.596256+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: 71252d5f5a654a77825c10c529b83ba1>: To evaluate training progress\n",
      "Value: <Storable: 0.21138830482959747>\n",
      "[2022-02-06T19:53:06.804698+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: df3bf655b9a842cfbfd6e5b490c0e435>: To evaluate training progress\n",
      "Value: <Storable: 0.21096400916576385>\n",
      "[2022-02-06T19:53:07.004165+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: 0d89244ec6ec4e979c949ea5609900ac>: To evaluate training progress\n",
      "Value: <Storable: 0.2109958976507187>\n",
      "[2022-02-06T19:53:07.224575+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: 9ff283a50d684ef685704930022b4c0e>: To evaluate training progress\n",
      "Value: <Storable: 0.21108801662921906>\n",
      "[2022-02-06T19:53:18.240798+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: 09b6462673a34da0bb3a2d0d9354737a>:\n",
      "Value: <Storable: 3814>\n",
      "[2022-02-06T19:53:18.395995+0000][CRITICAL][logger]][65548] Expected 2 or more dimensions (got 1)\n",
      "[2022-02-06T19:53:18.397031+0000][CRITICAL][logger]][65548] Expected 2 or more dimensions (got 1)\n",
      "Exception in callback AsyncIOEventEmitter._emit_run.<locals>._callback(<Task finishe...ons (got 1)')>) at C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\pyee\\_asyncio.py:57\n",
      "handle: <Handle AsyncIOEventEmitter._emit_run.<locals>._callback(<Task finishe...ons (got 1)')>) at C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\pyee\\_asyncio.py:57>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\pyee\\_asyncio.py\", line 64, in _callback\n",
      "    self.emit(\"error\", exc)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\pyee\\_base.py\", line 118, in emit\n",
      "    self._emit_handle_potential_error(event, args[0] if args else None)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\pyee\\_base.py\", line 88, in _emit_handle_potential_error\n",
      "    raise error\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\asyncio\\tasks.py\", line 280, in __step\n",
      "    result = coro.send(None)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\grid\\connections\\webrtc.py\", line 233, in on_message\n",
      "    await self.consumer(msg=message)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\grid\\connections\\webrtc.py\", line 449, in consumer\n",
      "    traceback_and_raise(e)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\logger.py\", line 61, in traceback_and_raise\n",
      "    raise e\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\grid\\connections\\webrtc.py\", line 434, in consumer\n",
      "    self.recv_immediate_msg_without_reply(msg=_msg)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\grid\\connections\\webrtc.py\", line 490, in recv_immediate_msg_without_reply\n",
      "    traceback_and_raise(e)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\logger.py\", line 61, in traceback_and_raise\n",
      "    raise e\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\grid\\connections\\webrtc.py\", line 485, in recv_immediate_msg_without_reply\n",
      "    self.node.recv_immediate_msg_without_reply(msg=msg)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\core\\node\\common\\node.py\", line 399, in recv_immediate_msg_without_reply\n",
      "    self.process_message(msg=msg, router=self.immediate_msg_without_reply_router)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\core\\node\\common\\node.py\", line 481, in process_message\n",
      "    result = service.process(\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\core\\node\\common\\service\\obj_action_service.py\", line 27, in process\n",
      "    msg.execute_action(node=node, verify_key=verify_key)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\core\\node\\common\\action\\function_or_constructor_action.py\", line 126, in execute_action\n",
      "    result = method(*upcasted_args, **upcasted_kwargs)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\torch\\nn\\functional.py\", line 2381, in nll_loss\n",
      "    raise ValueError(\"Expected 2 or more dimensions (got {})\".format(dim))\n",
      "ValueError: Expected 2 or more dimensions (got 1)\n",
      "[2022-02-06T19:53:18.400005+0000][CRITICAL][logger]][65548] execute_action on torch.Tensor.backward failed due to missing object at: <UID: fd4e0144aa054d0d942d4d4548b9e462>\n",
      "[2022-02-06T19:53:18.401979+0000][CRITICAL][logger]][65548] <class 'syft.core.store.store_memory.MemoryStore'> __delitem__ error <UID: 6fb1bbafe7084dcbbb0ebcfa9ce2944e>.\n",
      "[2022-02-06T19:53:18.406012+0000][CRITICAL][logger]][65548] execute_action on torch.Tensor.item failed due to missing object at: <UID: fd4e0144aa054d0d942d4d4548b9e462>\n",
      "[2022-02-06T19:53:18.411953+0000][CRITICAL][logger]][65548] <class 'syft.core.store.store_memory.MemoryStore'> __getitem__ error <UID: 852d32418d41421d92087421bfbdaf0f> <UID: 852d32418d41421d92087421bfbdaf0f>\n",
      "[2022-02-06T19:53:18.411953+0000][CRITICAL][logger]][65548] <UID: 852d32418d41421d92087421bfbdaf0f>\n",
      "[2022-02-06T19:53:18.412951+0000][CRITICAL][logger]][65548] <UID: 852d32418d41421d92087421bfbdaf0f>\n",
      "[2022-02-06T19:53:18.412951+0000][CRITICAL][logger]][65548] <UID: 852d32418d41421d92087421bfbdaf0f>\n",
      "Exception in callback AsyncIOEventEmitter._emit_run.<locals>._callback(<Task finishe...421bfbdaf0f>)>) at C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\pyee\\_asyncio.py:57\n",
      "handle: <Handle AsyncIOEventEmitter._emit_run.<locals>._callback(<Task finishe...421bfbdaf0f>)>) at C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\pyee\\_asyncio.py:57>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\pyee\\_asyncio.py\", line 64, in _callback\n",
      "    self.emit(\"error\", exc)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\pyee\\_base.py\", line 118, in emit\n",
      "    self._emit_handle_potential_error(event, args[0] if args else None)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\pyee\\_base.py\", line 88, in _emit_handle_potential_error\n",
      "    raise error\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\asyncio\\tasks.py\", line 280, in __step\n",
      "    result = coro.send(None)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\grid\\connections\\webrtc.py\", line 233, in on_message\n",
      "    await self.consumer(msg=message)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\grid\\connections\\webrtc.py\", line 449, in consumer\n",
      "    traceback_and_raise(e)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\logger.py\", line 61, in traceback_and_raise\n",
      "    raise e\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\grid\\connections\\webrtc.py\", line 434, in consumer\n",
      "    self.recv_immediate_msg_without_reply(msg=_msg)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\grid\\connections\\webrtc.py\", line 490, in recv_immediate_msg_without_reply\n",
      "    traceback_and_raise(e)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\logger.py\", line 61, in traceback_and_raise\n",
      "    raise e\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\grid\\connections\\webrtc.py\", line 485, in recv_immediate_msg_without_reply\n",
      "    self.node.recv_immediate_msg_without_reply(msg=msg)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\core\\node\\common\\node.py\", line 399, in recv_immediate_msg_without_reply\n",
      "    self.process_message(msg=msg, router=self.immediate_msg_without_reply_router)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\core\\node\\common\\node.py\", line 481, in process_message\n",
      "    result = service.process(\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\core\\node\\common\\service\\obj_action_service.py\", line 27, in process\n",
      "    msg.execute_action(node=node, verify_key=verify_key)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\core\\node\\common\\action\\run_class_method_action.py\", line 126, in execute_action\n",
      "    r_arg = node.store[arg.id_at_location]\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\core\\store\\store_memory.py\", line 66, in __getitem__\n",
      "    traceback_and_raise(e)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\logger.py\", line 61, in traceback_and_raise\n",
      "    raise e\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\core\\store\\store_memory.py\", line 63, in __getitem__\n",
      "    return self._objects[key]\n",
      "KeyError: <UID: 852d32418d41421d92087421bfbdaf0f>\n",
      "[2022-02-06T19:53:18.417937+0000][CRITICAL][logger]][65548] <class 'syft.core.store.store_memory.MemoryStore'> __getitem__ error <UID: 852d32418d41421d92087421bfbdaf0f> <UID: 852d32418d41421d92087421bfbdaf0f>\n",
      "[2022-02-06T19:53:18.418934+0000][CRITICAL][logger]][65548] <UID: 852d32418d41421d92087421bfbdaf0f>\n",
      "[2022-02-06T19:53:18.418934+0000][CRITICAL][logger]][65548] <UID: 852d32418d41421d92087421bfbdaf0f>\n",
      "[2022-02-06T19:53:18.419932+0000][CRITICAL][logger]][65548] <UID: 852d32418d41421d92087421bfbdaf0f>\n",
      "Exception in callback AsyncIOEventEmitter._emit_run.<locals>._callback(<Task finishe...421bfbdaf0f>)>) at C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\pyee\\_asyncio.py:57\n",
      "handle: <Handle AsyncIOEventEmitter._emit_run.<locals>._callback(<Task finishe...421bfbdaf0f>)>) at C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\pyee\\_asyncio.py:57>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\pyee\\_asyncio.py\", line 64, in _callback\n",
      "    self.emit(\"error\", exc)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\pyee\\_base.py\", line 118, in emit\n",
      "    self._emit_handle_potential_error(event, args[0] if args else None)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\pyee\\_base.py\", line 88, in _emit_handle_potential_error\n",
      "    raise error\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\asyncio\\tasks.py\", line 280, in __step\n",
      "    result = coro.send(None)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\grid\\connections\\webrtc.py\", line 233, in on_message\n",
      "    await self.consumer(msg=message)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\grid\\connections\\webrtc.py\", line 449, in consumer\n",
      "    traceback_and_raise(e)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\logger.py\", line 61, in traceback_and_raise\n",
      "    raise e\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\grid\\connections\\webrtc.py\", line 434, in consumer\n",
      "    self.recv_immediate_msg_without_reply(msg=_msg)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\grid\\connections\\webrtc.py\", line 490, in recv_immediate_msg_without_reply\n",
      "    traceback_and_raise(e)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\logger.py\", line 61, in traceback_and_raise\n",
      "    raise e\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\grid\\connections\\webrtc.py\", line 485, in recv_immediate_msg_without_reply\n",
      "    self.node.recv_immediate_msg_without_reply(msg=msg)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\core\\node\\common\\node.py\", line 399, in recv_immediate_msg_without_reply\n",
      "    self.process_message(msg=msg, router=self.immediate_msg_without_reply_router)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\core\\node\\common\\node.py\", line 481, in process_message\n",
      "    result = service.process(\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\core\\node\\domain\\service\\request_message.py\", line 222, in process\n",
      "    msg.object_tags.extend(node.store[msg.object_id]._tags)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\core\\store\\store_memory.py\", line 66, in __getitem__\n",
      "    traceback_and_raise(e)\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\logger.py\", line 61, in traceback_and_raise\n",
      "    raise e\n",
      "  File \"C:\\Users\\dylan\\anaconda3\\envs\\new_pysyft\\lib\\site-packages\\syft\\core\\store\\store_memory.py\", line 63, in __getitem__\n",
      "    return self._objects[key]\n",
      "KeyError: <UID: 852d32418d41421d92087421bfbdaf0f>\n",
      "[2022-02-06T19:53:18.446894+0000][CRITICAL][logger]][65548] <class 'syft.core.store.store_memory.MemoryStore'> __delitem__ error <UID: fd4e0144aa054d0d942d4d4548b9e462>.\n",
      "[2022-02-06T19:53:18.448887+0000][CRITICAL][logger]][65548] <class 'syft.core.store.store_memory.MemoryStore'> __delitem__ error <UID: 852d32418d41421d92087421bfbdaf0f>.\n",
      "[2022-02-06T19:53:18.450878+0000][CRITICAL][logger]][65548] <class 'syft.core.store.store_memory.MemoryStore'> __delitem__ error <UID: 0114271705974afaa13937fea430adfb>.\n",
      "[2022-02-06T19:54:30.019340+0000][CRITICAL][logger]][65548] <class 'syft.core.store.store_memory.MemoryStore'> __delitem__ error <UID: 91571401be8046fb96dd10f8a41871b6>.\n",
      "[2022-02-06T19:54:30.020339+0000][CRITICAL][logger]][65548] <class 'syft.core.store.store_memory.MemoryStore'> __delitem__ error <UID: 47dcf8c014f64477897523548ddc10bb>.\n",
      "[2022-02-06T19:57:21.642329+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: beb52eaf91af40daa2159bcd99456e55>: To run test and inference locally\n",
      "Value: <Storable: False>\n",
      "[2022-02-06T19:57:25.487759+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: ed8c5a5e2a92443b8d7e684cd39766ad>: To evaluate training progress\n",
      "Value: <Storable: 0.7800891399383545>\n",
      "[2022-02-06T19:57:25.691215+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: 95e183ce48be418a835404f756b38025>: To evaluate training progress\n",
      "Value: <Storable: 0.22144781053066254>\n",
      "[2022-02-06T19:57:25.907635+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: 608f7157298c47fc9b512b28e2d2bc55>: To evaluate training progress\n",
      "Value: <Storable: 0.3091380000114441>\n",
      "[2022-02-06T19:57:26.113114+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: cd673901332f4ea09906bf9df793fc77>: To evaluate training progress\n",
      "Value: <Storable: 0.3265496790409088>\n",
      "[2022-02-06T19:57:26.331502+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: c5fceb4604bd4e1aa23f7b6bf2200c80>: To evaluate training progress\n",
      "Value: <Storable: 0.29365938901901245>\n",
      "[2022-02-06T19:57:26.535982+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: ea96662687ff4e6ab9f1339fca1604eb>: To evaluate training progress\n",
      "Value: <Storable: 0.24737048149108887>\n",
      "[2022-02-06T19:57:26.740435+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: 1b04f49088084f528252800fdcedf7b1>: To evaluate training progress\n",
      "Value: <Storable: 0.2191561609506607>\n",
      "[2022-02-06T19:57:26.959821+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: f6de99f899824f26892963ee9431e832>: To evaluate training progress\n",
      "Value: <Storable: 0.24765613675117493>\n",
      "[2022-02-06T19:57:27.174246+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: a79161dc48254b02a46ab7c5951360b3>: To evaluate training progress\n",
      "Value: <Storable: 0.250692754983902>\n",
      "[2022-02-06T19:57:27.385725+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: b9ada6f460db49c8b585b4e7b7bdf8b5>: To evaluate training progress\n",
      "Value: <Storable: 0.2244962751865387>\n",
      "[2022-02-06T19:57:27.595121+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: a4ac6533288241fb82894c8bdd642ce1>: To evaluate training progress\n",
      "Value: <Storable: 0.22083115577697754>\n",
      "[2022-02-06T19:57:27.845451+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: 908c6df5594e4838b8e7428383550de6>: To evaluate training progress\n",
      "Value: <Storable: 0.2289872020483017>\n",
      "[2022-02-06T19:57:28.075835+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: 8705c054f50c46558e3359b47b3b1c21>: To evaluate training progress\n",
      "Value: <Storable: 0.23462852835655212>\n",
      "[2022-02-06T19:57:28.304225+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: 063694e23e98415c8f9a70f5026ccb15>: To evaluate training progress\n",
      "Value: <Storable: 0.2342466115951538>\n",
      "[2022-02-06T19:57:28.529621+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: e469ade708344a43ba16428f8f10a11b>: To evaluate training progress\n",
      "Value: <Storable: 0.2285839319229126>\n",
      "[2022-02-06T19:57:28.757013+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: 67c245855d82400ba25b2675ca6a6b27>: To evaluate training progress\n",
      "Value: <Storable: 0.22083336114883423>\n",
      "[2022-02-06T19:57:28.981412+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: b0ee2b1a9cba4c229f045f07b6e3d2ac>: To evaluate training progress\n",
      "Value: <Storable: 0.21765534579753876>\n",
      "[2022-02-06T19:57:29.200825+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: f57aa54319bb48e9bc8c26bc0516d997>: To evaluate training progress\n",
      "Value: <Storable: 0.2209630161523819>\n",
      "[2022-02-06T19:57:29.418244+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: a7c824f0f47d40a7a43d5e5dd9a0af70>: To evaluate training progress\n",
      "Value: <Storable: 0.22576256096363068>\n",
      "[2022-02-06T19:57:29.625692+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: 98d74c0468e44f7c86ecbe5dfa5fd97d>: To evaluate training progress\n",
      "Value: <Storable: 0.22472520172595978>\n",
      "[2022-02-06T19:57:29.842110+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: 324a2aa22f594a329eb0b4338f1af74a>: To evaluate training progress\n",
      "Value: <Storable: 0.21904464066028595>\n",
      "[2022-02-06T19:57:30.983059+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: 3359b082a7c74c68af6bb304385433ab>: To evaluate training progress\n",
      "Value: <Storable: 0.2164539396762848>\n",
      "[2022-02-06T19:57:31.198483+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: 2dc5134f11444729b995e58fe56bedfe>: To evaluate training progress\n",
      "Value: <Storable: 0.21651579439640045>\n",
      "[2022-02-06T19:57:31.419890+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: 397cbe46c7664a81a65a08e46959255d>: To evaluate training progress\n",
      "Value: <Storable: 0.2184259295463562>\n",
      "[2022-02-06T19:57:31.629328+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: 586016c253e44b9cb9258ee105613062>: To evaluate training progress\n",
      "Value: <Storable: 0.2197599560022354>\n",
      "[2022-02-06T19:59:03.716678+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: 28496dcedc214dcbb5cfc75493b74c31>: To run test and inference locally\n",
      "Value: <Storable: False>\n",
      "[2022-02-06T19:59:17.753404+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: 5bd79882560d46adaf75b76df2c84a04>: To evaluate training progress\n",
      "Value: <Storable: 1.0231220722198486>\n",
      "[2022-02-06T19:59:17.957857+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: 75bfde37d6c34afda69b27524758a717>: To evaluate training progress\n",
      "Value: <Storable: 1.023207664489746>\n",
      "[2022-02-06T19:59:18.176273+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: a3917c5e2fa94ac09e730527bcd2bfb6>: To evaluate training progress\n",
      "Value: <Storable: 1.0231735706329346>\n",
      "[2022-02-06T19:59:18.378732+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: 151210c6f8dd4635b687321eae40b79c>: To evaluate training progress\n",
      "Value: <Storable: 1.023134708404541>\n",
      "[2022-02-06T19:59:18.589170+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: 557850e2b672433d847c8bae05c51894>: To evaluate training progress\n",
      "Value: <Storable: 1.0231881141662598>\n",
      "[2022-02-06T19:59:19.726127+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: 98e0dc3ca30647bea7de5c1420bac20b>: To evaluate training progress\n",
      "Value: <Storable: 1.0231542587280273>\n",
      "[2022-02-06T19:59:19.939556+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: beb31d83c41d4e65bc500122a3526a36>: To evaluate training progress\n",
      "Value: <Storable: 1.0231411457061768>\n",
      "[2022-02-06T19:59:20.169959+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: 627ce3a445a24d01b79331a4c3630710>: To evaluate training progress\n",
      "Value: <Storable: 1.0232133865356445>\n",
      "[2022-02-06T19:59:20.390350+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: a2fcf7ae6fd645aba77cd67ed427f3f0>: To evaluate training progress\n",
      "Value: <Storable: 1.0231777429580688>\n",
      "[2022-02-06T19:59:20.611759+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: 4f09e58961d54cfb81a864f28ba37f6c>: To evaluate training progress\n",
      "Value: <Storable: 1.0231690406799316>\n",
      "[2022-02-06T19:59:20.828178+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: f90eca94fb0b4ae4972c69fec5d7ea57>: To evaluate training progress\n",
      "Value: <Storable: 1.0231987237930298>\n",
      "[2022-02-06T19:59:21.056568+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: e36d97dfc8c2414d8ffed78b25d5d20c>: To evaluate training progress\n",
      "Value: <Storable: 1.023136019706726>\n",
      "[2022-02-06T19:59:21.268999+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: 0d0865e083ef4ccb8f1bbfb294ddeff0>: To evaluate training progress\n",
      "Value: <Storable: 1.0231727361679077>\n",
      "[2022-02-06T19:59:21.489410+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: 19731bc27e2244cc98e13664bdb91442>: To evaluate training progress\n",
      "Value: <Storable: 1.0232144594192505>\n",
      "[2022-02-06T19:59:21.697853+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: 9fb7c589079c41169b72200d46ca8a96>: To evaluate training progress\n",
      "Value: <Storable: 1.023215889930725>\n",
      "[2022-02-06T19:59:21.908289+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: 32c347eec05f4b02ba9991797dae4f74>: To evaluate training progress\n",
      "Value: <Storable: 1.023177146911621>\n",
      "[2022-02-06T19:59:22.122716+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: 3ae9052c599f471fb5884bb0a4bf8450>: To evaluate training progress\n",
      "Value: <Storable: 1.0231674909591675>\n",
      "[2022-02-06T19:59:22.378033+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: b6b3ea34e6e54f57bb0c829fca6543b0>: To evaluate training progress\n",
      "Value: <Storable: 1.0232282876968384>\n",
      "[2022-02-06T19:59:22.603430+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: a5d4bddd870647bf8adf8374be6542bc>: To evaluate training progress\n",
      "Value: <Storable: 1.0231133699417114>\n",
      "[2022-02-06T19:59:22.840796+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: da6f69f3adc54e9793c07f80ffa51773>: To evaluate training progress\n",
      "Value: <Storable: 1.0231302976608276>\n",
      "[2022-02-06T19:59:23.081154+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: 2485dc3215f44fbea6f9e74934c85a43>: To evaluate training progress\n",
      "Value: <Storable: 1.023250699043274>\n",
      "[2022-02-06T19:59:24.195174+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: ded96b4f51834b459d9e79efc156b44c>: To evaluate training progress\n",
      "Value: <Storable: 1.0232435464859009>\n",
      "[2022-02-06T19:59:24.413589+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: 275d9b56f1124db684ab4742a033203b>: To evaluate training progress\n",
      "Value: <Storable: 1.0231901407241821>\n",
      "[2022-02-06T19:59:24.651951+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: 20183fdcd48840ceb4300163a75031bc>: To evaluate training progress\n",
      "Value: <Storable: 1.0231589078903198>\n",
      "[2022-02-06T19:59:24.880340+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: 3ec819cf59f04d53b48155a75cb4654c>: To evaluate training progress\n",
      "Value: <Storable: 1.023186445236206>\n",
      "[2022-02-06T20:00:23.279888+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: 2f99120a27c14e28bfec7b7da66b4ea4>: To run test and inference locally\n",
      "Value: <Storable: False>\n",
      "[2022-02-06T20:00:36.232729+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: 4f9f8230fb574a82b6cefbd6fe1e8f32>: To evaluate training progress\n",
      "Value: <Storable: 0.9196323752403259>\n",
      "[2022-02-06T20:00:36.516937+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: 96e0ad4e40fe43599f499330af3b93ef>: To evaluate training progress\n",
      "Value: <Storable: 0.9189258217811584>\n",
      "[2022-02-06T20:00:36.750311+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: 3bdd2ec1eaf04f45a264b714240f2213>: To evaluate training progress\n",
      "Value: <Storable: 0.918186604976654>\n",
      "[2022-02-06T20:00:36.984684+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: 0376e8600ae34f2398f1b6897c5176a9>: To evaluate training progress\n",
      "Value: <Storable: 0.9175127744674683>\n",
      "[2022-02-06T20:00:37.218061+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: 6c391d1953b747d8a0b901d38a8e1db4>: To evaluate training progress\n",
      "Value: <Storable: 0.9167072772979736>\n",
      "[2022-02-06T20:00:37.469388+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: 28647af1f6474512ae56bccc709044cb>: To evaluate training progress\n",
      "Value: <Storable: 0.916002094745636>\n",
      "[2022-02-06T20:00:37.697777+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: 6d10d90072174db99e8b7dffe3c651a8>: To evaluate training progress\n",
      "Value: <Storable: 0.9153159856796265>\n",
      "[2022-02-06T20:00:37.923174+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: 4e5230a661164056a1b62066cfcba0f4>: To evaluate training progress\n",
      "Value: <Storable: 0.9145039916038513>\n",
      "[2022-02-06T20:00:38.137599+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: 6f652550bf194d3394f2aab5b856dfef>: To evaluate training progress\n",
      "Value: <Storable: 0.9137281179428101>\n",
      "[2022-02-06T20:00:38.359008+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: 2ff856d67b5849959441ac6254b68854>: To evaluate training progress\n",
      "Value: <Storable: 0.9130131006240845>\n",
      "[2022-02-06T20:00:38.571469+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: a495375973ad4b2ba6da6409ec80c0b2>: To evaluate training progress\n",
      "Value: <Storable: 0.9123355746269226>\n",
      "[2022-02-06T20:00:38.789855+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: c4259555b2d74044b8906c50ef75e611>: To evaluate training progress\n",
      "Value: <Storable: 0.9115486741065979>\n",
      "[2022-02-06T20:00:39.000292+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: c041a8b79aeb490383f47809de24d48e>: To evaluate training progress\n",
      "Value: <Storable: 0.9107548594474792>\n",
      "[2022-02-06T20:00:39.216715+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: 55a4e274c5774876aef96f2667b4df57>: To evaluate training progress\n",
      "Value: <Storable: 0.9099021553993225>\n",
      "[2022-02-06T20:00:39.441112+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: 680fad6971e14982aaa1ddb610f04309>: To evaluate training progress\n",
      "Value: <Storable: 0.9092625379562378>\n",
      "[2022-02-06T20:00:39.659529+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: d9d82963482940378844fa0815a06ebb>: To evaluate training progress\n",
      "Value: <Storable: 0.908478319644928>\n",
      "[2022-02-06T20:00:39.892904+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: a271946787e245dd9b4b8a6a8911f0ca>: To evaluate training progress\n",
      "Value: <Storable: 0.9078970551490784>\n",
      "[2022-02-06T20:00:40.125282+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: f3735cd6618a4825b4270ab7ddd8ad46>: To evaluate training progress\n",
      "Value: <Storable: 0.9070344567298889>\n",
      "[2022-02-06T20:00:40.357660+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: efe6ae913ed145eb85c962aa992f588f>: To evaluate training progress\n",
      "Value: <Storable: 0.9063320159912109>\n",
      "[2022-02-06T20:00:40.588044+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: 200e31f1b7e04a52b40b46f4770b7978>: To evaluate training progress\n",
      "Value: <Storable: 0.9056554436683655>\n",
      "[2022-02-06T20:00:40.810449+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: 1d7fe06b0d9e44b39d55e1cd3e10d616>: To evaluate training progress\n",
      "Value: <Storable: 0.9048944711685181>\n",
      "[2022-02-06T20:00:41.022881+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: c9ddd5934d0242b6a45c0b43a947e142>: To evaluate training progress\n",
      "Value: <Storable: 0.9041736125946045>\n",
      "[2022-02-06T20:00:41.234316+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: 844c578dccc54942bff898e892f0d57d>: To evaluate training progress\n",
      "Value: <Storable: 0.9032872319221497>\n",
      "[2022-02-06T20:00:41.464699+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: 041787df5d5e455ba0e1bb5adadf66e6>: To evaluate training progress\n",
      "Value: <Storable: 0.9027141332626343>\n",
      "[2022-02-06T20:00:41.700071+0000][CRITICAL][logger]][65548] > HANDLER Request <UID: c339e8d2a49642739b37acb78244a14c>: To evaluate training progress\n",
      "Value: <Storable: 0.901991605758667>\n"
     ]
    }
   ],
   "source": [
    "duet.requests.add_handler(\n",
    "    action=\"accept\",\n",
    "    print_local=True,  # print the result in your notebook\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "assigned-tomato",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
